### ISSUE TITLE
temp file not found

### ISSUE THREAD

**Issue by SamuelTissot** [NLKNguyen/pipe-mysql.vim#5]
Hello

very interesting your plugin, thanks.

I am running into an issue with the temp file

`._temp_pipemysql_ac59330d: No such file or directory`

the issue seems to around those lines

***file: pipe-mysql.vim***
```
  184   call writefile([g:PipeGetCurrentLine()], s:tempfilename, 'w')
  185
  186   let l:shell_command .= ' -t < ' . s:tempfilename
```

I am quite newbie at vim so any pointer would be great. thanks

**Comment by NLKNguyen** [comment]
Hi, I'll come back to this at some point. I currently don't have MySQL setup to test.

In the meantime, would you please provide what OS and version of Vim that you are using?

**Comment by SamuelTissot** [comment]
Thanks

MacOs Sierra 10.12.6

**Comment by SamuelTissot** [comment]
@NLKNguyen Thanks
